### PR TITLE
Add mac llvm installing to README

### PR DESCRIPTION
**Pull request by hsk**

### CODE REVIEW

**Comment by rhysd** [comment]
`llvm38` is in [homebrew-versions](https://github.com/Homebrew/homebrew-versions). So we can't install it by only the command.

```
brew install homebrew/versions/llvm38
```

is a better way. It enables to install LLVM 3.8 even if homebrew-versions is not tapped.

**Comment by equal-l2** [comment]
Isn't this enough?
```
brew install llvm
```

This will install LLVM 3.9.

**Comment by rhysd** [comment]
@equal-l2 

Currently yes. But in near future, it'll be no becuase LLVM 4.0 will be released. We can't control version of LLVM installed with `brew install llvm`.

**Comment by equal-l2** [comment]
@rhysd 
Then this is suitable.

```
brew install llvm@3.8
```

Some part of versioned formulae are now in homebrew-core repository, so you won't need to tap anymore.

**Comment by rhysd** [comment]
oh, I didn't know the `@version` spec. It looks better. So the instruction should be `brew install llvm@3.8` as you said.

**Comment by equal-l2** [comment]
@hsk Ping?

**Pull request closed without merging**
